/* ════════════════════════════════════════════════════════════════
   JAM Intelligence — network editions manifest.
   GENERATED by gephi/scripts/jam_network_pipeline.py — edit by hand only
   to correct mistakes. Pages render the newest edition + archives from it.
   ════════════════════════════════════════════════════════════════ */

const NETWORKS = {
  "ai": {
    "name": "AI Landscape",
    "sectorPage": "ai_transformation_for_smes.html",
    "archivePage": "network_archive_ai.html",
    "editions": [
      {
        "date": "2026-07-17",
        "file": "web_assets/jam_ai_network_2026-07-17.png",
        "thumb": "web_assets/archive/thumbs/jam_ai_network_2026-07-17.png",
        "events": 170,
        "nodes": 75
      },
      {
        "date": "2026-06-12",
        "file": "web_assets/archive/jam_ai_landscape_network_4k.png",
        "thumb": null,
        "events": null,
        "nodes": null
      }
    ]
  },
  "economy": {
    "name": "Economy & Monetary",
    "sectorPage": "eu_tech_economics.html",
    "archivePage": "network_archive_eu.html",
    "editions": [
      {
        "date": "2026-07-17",
        "file": "web_assets/jam_economy_network_2026-07-17.png",
        "thumb": "web_assets/archive/thumbs/jam_economy_network_2026-07-17.png",
        "events": 48,
        "nodes": 24
      }
    ]
  },
  "energy": {
    "name": "Energy & AI Buildout",
    "sectorPage": "energy_ai_buildout.html",
    "archivePage": "network_archive_energy.html",
    "editions": []
  }
};
